[[streams]]
city   = "Varied"
label  = "yo"
link   = "https://twitch.tv/woke"
notes  = "Live protest streams from around the world."
source = "woke.net"

[[streams]]
kind = "video"
label = "Tyrant Finder U.K."
link = "https://www.youtube.com/watch?v=41ssraiDW3A"

[[streams]]
kind = "video"
label = "ResistanceGB"
link = "https://www.youtube.com/watch?v=2J6RLvJ5uM8"

[[streams]]
kind = "video"
label = "Immortal Aliens"
link = "https://www.youtube.com/watch?v=YmW27Nj0_3A"